/**
 * ParkFlow Branding Configuration
 * ================================
 * Change this ONE file to rebrand the entire application for any client.
 * 
 * Current Client: Saddar Co-Operative Market LTD.
 * 
 * HOW TO REBRAND FOR NEW CLIENT:
 * 1. Change plaza name, address, phone
 * 2. Update slip settings
 * 3. Change colors (optional)
 * 4. Replace logo file in /public/logo.png (optional)
 * 5. Done! Entire app rebrands automatically.
 */

export const BRANDING = {
  // ============================================
  // PLAZA IDENTITY
  // ============================================
  plaza: {
    name: "Saddar Co-Operative Market LTD.",
    shortName: "Saddar Market",
    address: "Abdullah Haroon Road Saddar Karachi 74400",
    phone: "021-35684912",
    email: "",
    website: "",
  },

  // ============================================
  // APP BRANDING (Sidebar + Login)
  // ============================================
  app: {
    name: "Saddar Co-Operative Market LTD.",
    tagline: "Smart Parking Management",
    version: "v3.0",
    logo: null as string | null, // Set to "/logo.png" when logo file exists in /public/
    // If null, shows default ParkFlow icon
  },

  // ============================================
  // PARKING SLIP SETTINGS
  // ============================================
  slip: {
    title: "Daily Parking Receipt",
    showPlazaName: true,
    showAddress: true,
    showQR: true,
    showBarcode: false,
    footer: "The management is not responsible\nfor any vehicle damage or loss.",
    width: "80mm" as "58mm" | "80mm", // Thermal printer width
    dateFormat: "DD-MM-YY", // Pakistani format
    timeFormat: "hh:mm A", // 12-hour with AM/PM
  },

  // ============================================
  // COLOR THEME
  // ============================================
  theme: {
    // Primary gradient (sidebar, buttons, hero sections)
    primary: "blue",       // blue | emerald | red | slate | navy
    secondary: "purple",   // purple | teal | orange | indigo | gold

    // Gradient CSS classes (auto-generated from primary/secondary)
    gradient: "from-blue-500 via-purple-500 to-pink-500",
    gradientHover: "from-blue-600 via-purple-600 to-pink-600",
    gradientSubtle: "from-blue-100 via-purple-100 to-pink-100",

    // Accent colors for specific elements
    checkinColor: "emerald",   // Check-in button/badge
    checkoutColor: "amber",    // Check-out button/badge
    permanentColor: "emerald", // Permanent vehicle indicators
    guestColor: "blue",        // Guest vehicle indicators
    revenueColor: "green",     // Revenue numbers
    dangerColor: "rose",       // Deactivate/delete actions
  },

  // ============================================
  // DASHBOARD SETTINGS
  // ============================================
  dashboard: {
    refreshInterval: 30000, // 30 seconds auto-refresh
    showRevenue: true,      // Revenue section visibility
    revenueAdminOnly: true, // If true, only admin sees revenue
    showVehicleTypeBreakdown: true, // Car/Bike/Auto separate counts
  },

  // ============================================
  // REPORT SETTINGS
  // ============================================
  reports: {
    showPlateNumbers: true,     // Show plate column in reports
    separateGuestPermanent: true, // Separate sections in PDF
    showLogo: true,             // Logo in PDF header
    pdfTitle: "Parking Report",
    pdfFooter: "Generated by ParkFlow — Saddar Co-Operative Market LTD.",
  },

  // ============================================
  // VEHICLE TYPES (display names)
  // ============================================
  vehicleLabels: {
    car: "Car",
    bike: "Motorcycle",
    auto: "Auto Rickshaw",
    truck: "Truck/Van",
  } as Record<string, string>,
};

// Helper function to get full gradient class
export function getGradient(type: "primary" | "subtle" | "hover" = "primary"): string {
  switch (type) {
    case "subtle": return BRANDING.theme.gradientSubtle;
    case "hover": return BRANDING.theme.gradientHover;
    default: return BRANDING.theme.gradient;
  }
}

// Helper to check if feature is visible for role
export function isVisibleForRole(feature: string, role: string): boolean {
  if (feature === "revenue") {
    if (!BRANDING.dashboard.showRevenue) return false;
    if (BRANDING.dashboard.revenueAdminOnly && role !== "admin") return false;
    return true;
  }
  return true;
}

export default BRANDING;
